services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - ./node_js/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  caddy:
    image: caddy:2-alpine
    container_name: preview-caddy
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${CADDY_PORT}:${CADDY_PORT}"
      - "${CADDY_PORT_2}:${CADDY_PORT_2}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - preview_proxy

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  backend:
    name: preview_backend

  preview_proxy:
    name: preview_proxy