services:
  next_js:
    build: 
      context: ./advanced_next_js
    env_file:
      - ./advanced_next_js/.env
      - ./.env
    networks:
      - pr_backend
      - preview_proxy
    depends_on:
      node_js:
        condition: service_healthy

  node_js:
    build:
      context: ./node_js
    env_file:
      - ./node_js/.env
      - ./.env
    networks:
      - pr_backend
      - preview_backend
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "health_check.js"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  pr_backend:

  preview_proxy:
    external: true
    name: preview_proxy

  preview_backend:
    external: true
    name: preview_backend